import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Link from "next/link";
import { Layout, Menu } from "antd";
import { Footer, Header, Content } from "antd/es/layout/layout";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const items = [
  {key: 0, label: <Link href={'/'}>Home</Link>},
  {key: 1, label: <Link href={'/posts'}>Posts</Link>},
  {key: 2, label: <Link href={'/albums'}>Albums</Link>},
  {key: 3, label: <Link href={'/todos'}>Todos</Link>},
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry >
          <Layout>
            <Header>
              <Menu
              theme="dark"
              mode="horizontal"
              defaultSelectedKeys={['0']}
              items={items}
              style={{ flex: 1, minWidth: 0}}
              />
            </Header>
            <Content>{children}</Content>
            <Footer>Footer</Footer>
          </Layout>     
        </AntdRegistry>
      </body>
    </html>
  );
}
